version: '3'

services:
  app:
    build: 
      context: .
    env_file:
      - .env
    ports:
      - "1026:1026"
    volumes:
      - .:/app
    command: bash -c "python3 main.py"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    env_file:
      - .env
    command: server --console-address ":9090" /data
    volumes:
      - ./minio/data:/data
      - ./minio/conf:/root/.minio


networks:
  default:
    external: true
    name: 'fa_2'
