version: '3'

services:
  app:
    build: 
      context: .
    environment:
      - database_url=postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - "1026:1026"
    volumes:
      - .:/app
    command: bash -c "poetry run python3 src/app/main.py"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
